### ISSUE TITLE
To Disable Custom Control

### ISSUE THREAD

**Issue by karthickDhanapal** [rexkenley/d365MultipleLinesHTML#1]
Hi,

Loaded the custom control in a text field but setting disabled for attribute , custom control is not disabling

**Comment by rexkenley** [comment]
Thanks for reporting this issue. I have made the code fixes.
[Fix setDisabled](https://github.com/rexkenley/d365MultipleLinesHTML/commit/6c531d9307ec4e8fdd34bfe03c811a5e2463692f

Please confirm that it is working for you by closing this issue. Thanks again.

**Comment by karthickDhanapal** [comment]
Thank you so much @rexkenley . It is working now.
