### ISSUE TITLE
Control not visible

### ISSUE THREAD

**Issue by TobiasKoller** [rexkenley/d365MultipleLinesHTML#4]
hi,

I've tried your control in our test-online-environment.
The build process and installation was successful.
I also could choose the control from the "custom-control"-Menu.
But when I load the form, the control is not visible.

**Comment by rexkenley** [comment]
Hi Tobias

Can you please list the crm version, browser and maybe a screen shot? Thanks!

**Comment by TobiasKoller** [comment]
sure. I only have one multiline-Field on the form.

Dynamics CE Online 1710 (9.1.0.18647) 
You use TinyMCE right? this is not free anymore I think. Can this be a problem?
![1](https://user-images.githubusercontent.com/15647346/85366245-3c67a980-b527-11ea-9eec-d761c2003670.png)
![2](https://user-images.githubusercontent.com/15647346/85366255-3ffb3080-b527-11ea-87af-e49df321608c.png)

**Comment by rexkenley** [comment]
Hi Tobias

Sorry for the delay. I just released a fix. Please let me know if this works for you.

**Comment by rexkenley** [comment]
Tobias

I am going to close this issue assuming that the issue has been resolved. Please let me know if this is not the case.
